AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - '**/Gemfile'
    - '**/Gemfile.lock'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bundle_bin/*'
    - 'bin/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  # RunRailsCops: true

# Enable Japanese comments
Style/AsciiComments:
  Enabled: false

# Allow class with no document
Style/Documentation:
  Enabled: false

# In classes and modules methods after 'private' and 'protected'
# should be indented one step more
Style/IndentationConsistency:
  EnforcedStyle: rails

# 'inject {|a, e| }' is too short
Style/SingleLineBlockParams:
  Enabled: false

# Allow multiple spaces before args
Style/SingleSpaceBeforeFirstArg:
  Enabled: false

# Use double quotes
StringLiterals:
  EnforcedStyle: double_quotes
