AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - '**/Gemfile'
    - '**/Gemfile.lock'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bundle_bin/*'
    - 'bin/*'
    - 'vendor/**/*'
  DisplayCopNames: true

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

# Enable Japanese comments
Style/AsciiComments:
  Enabled: false

# Allow nested style like `ActiveSupport::TestCase`
Style/ClassAndModuleChildren:
  Enabled: false

# Allow class with no document
Style/Documentation:
  Enabled: false

# In classes and modules methods after 'private' and 'protected'
# should be indented one step more
Style/IndentationConsistency:
  EnforcedStyle: rails

# 'inject {|a, e| }' is too short
Style/SingleLineBlockParams:
  Enabled: false

# Use double quotes
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Put comma after last item of multiline arguments and array/hash
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
