# https://github.com/sasstools/sass-lint
options:
  formatter: stylish
files:
  include: '**/*.sass'
rules:
  # Extends
  placeholder-in-extend: 0

  # Line Spacing
  single-line-per-selector: 0
  empty-line-between-blocks: 0
  # Disallows
  no-color-literals: 0
  no-css-comments: 0
  no-ids: 0
  no-important: 0
  no-qualifying-elements:
    - 1
    -
      allow-element-with-class: true

  # Nesting
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  quotes:
    - 1
    -
      style: double
