scss_files: "**/*.scss"
linters:
  ColorVariable:
    enabled: false
  LeadingZero:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  QualifyingElement:
    enabled: false
  StringQuotes:
    enabled: true
    style: double_quotes
